Update README.md
Python 3.6 causes:
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.6'
Ref: https://github.com/pre-commit/pre-commit/issues/1375